import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="p-5">
        {children}
        <footer className="flex text-white justify-center">
          <p>Copyright &copy; 2024 ASL Game</p>
        </footer>
      </body>
    </html>
  );
}
